package templates

var envtabTemplates = LoadoutTemplates{
	Templates: map[string]LoadoutTemplate{
		"aws": {
			Description: "Amazon Web Services Template",
			Entries: []string{
				"AWS_ACCESS_KEY_ID",
				"AWS_CA_BUNDLE",
				"AWS_CLI_AUTO_PROMPT",
				"AWS_CLI_FILE_ENCODING",
				"AWS_CONFIG_FILE",
				"AWS_DATA_PATH",
				"AWS_DEFAULT_OUTPUT",
				"AWS_DEFAULT_REGION",
				"AWS_EC2_METADATA_DISABLED",
				"AWS_ENDPOINT_URL",
				"AWS_ENDPOINT_URL_<SERVICE>",
				"AWS_IGNORE_CONFIGURED_ENDPOINT_URLS",
				"AWS_MAX_ATTEMPTS",
				"AWS_METADATA_SERVICE_NUM_ATTEMPTS",
				"AWS_METADATA_SERVICE_TIMEOUT",
				"AWS_PAGER",
				"AWS_PROFILE",
				"AWS_REGION",
				"AWS_RETRY_MODE",
				"AWS_ROLE_ARN",
				"AWS_ROLE_SESSION_NAME",
				"AWS_SECRET_ACCESS_KEY",
				"AWS_SESSION_TOKEN",
				"AWS_SHARED_CREDENTIALS_FILE",
				"AWS_USE_DUALSTACK_ENDPOINT",
				"AWS_USE_FIPS_ENDPOINT",
				"AWS_WEB_IDENTITY_TOKEN_FILE",
			},
		},
		"gcp": {
			Description: "Google Cloud Platform Template",
			Entries: []string{
				"GOOGLE_APPLICATION_CREDENTIALS",
				"GCLOUD_PROJECT",
				"GCP_PROJECT",
				"GOOGLE_CLOUD_PROJECT",
				"GCLOUD_REGION",
				"GCP_REGION",
				"GOOGLE_CLOUD_REGION",
				"GCLOUD_ZONE",
				"GCP_ZONE",
				"GOOGLE_CLOUD_ZONE",
				"CLOUDSDK_CORE_PROJECT",
				"CLOUDSDK_COMPUTE_REGION",
				"CLOUDSDK_COMPUTE_ZONE",
				"CLOUDSDK_CONFIG",
				"CLOUDSDK_ACTIVE_CONFIG_NAME",
			},
		},
		"azure": {
			Description: "Microsoft Azure Template",
			Entries: []string{
				"AZURE_CLIENT_ID",
				"AZURE_CLIENT_SECRET",
				"AZURE_TENANT_ID",
				"AZURE_SUBSCRIPTION_ID",
				"AZURE_RESOURCE_GROUP",
				"AZURE_LOCATION",
				"AZURE_STORAGE_ACCOUNT",
				"AZURE_STORAGE_KEY",
				"AZURE_STORAGE_CONNECTION_STRING",
				"AZURE_KEYVAULT_URL",
			},
		},
		"pgsql": {
			Description: "PostgreSQL Database Template",
			Entries: []string{
				"PGHOST",
				"PGPORT",
				"PGDATABASE",
				"PGUSER",
				"PGPASSWORD",
				"PGPASSFILE",
				"PGSSLMODE",
				"PGSSLROOTCERT",
				"PGSSLKEY",
				"PGSSLCERT",
				"PGAPPNAME",
				"PGCONNECT_TIMEOUT",
			},
		},
		"mysql": {
			Description: "MySQL Database Template",
			Entries: []string{
				"MYSQL_HOST",
				"MYSQL_PORT",
				"MYSQL_DATABASE",
				"MYSQL_USER",
				"MYSQL_PASSWORD",
				"MYSQL_ROOT_PASSWORD",
				"MYSQL_SOCKET",
				"MYSQL_SSL_CA",
				"MYSQL_SSL_CERT",
				"MYSQL_SSL_KEY",
				"MYSQL_TLS_VERSION",
			},
		},
		"mongodb": {
			Description: "MongoDB Database Template",
			Entries: []string{
				"MONGODB_URI",
				"MONGODB_HOST",
				"MONGODB_PORT",
				"MONGODB_DATABASE",
				"MONGODB_USERNAME",
				"MONGODB_PASSWORD",
				"MONGODB_AUTH_SOURCE",
				"MONGODB_REPLICA_SET",
				"MONGODB_SSL",
				"MONGODB_SSL_CA_FILE",
			},
		},
		"elasticsearch": {
			Description: "Elasticsearch Template",
			Entries: []string{
				"ELASTICSEARCH_HOST",
				"ELASTICSEARCH_PORT",
				"ELASTICSEARCH_URL",
				"ELASTICSEARCH_USERNAME",
				"ELASTICSEARCH_PASSWORD",
				"ELASTICSEARCH_SSL",
				"ELASTICSEARCH_SSL_VERIFY",
				"ELASTICSEARCH_CA_CERT",
				"ELASTICSEARCH_INDEX",
			},
		},
		"kafka": {
			Description: "Apache Kafka Template",
			Entries: []string{
				"KAFKA_BOOTSTRAP_SERVERS",
				"KAFKA_BROKER",
				"KAFKA_HOST",
				"KAFKA_PORT",
				"KAFKA_TOPIC",
				"KAFKA_GROUP_ID",
				"KAFKA_CLIENT_ID",
				"KAFKA_SECURITY_PROTOCOL",
				"KAFKA_SASL_MECHANISM",
				"KAFKA_SASL_USERNAME",
				"KAFKA_SASL_PASSWORD",
				"KAFKA_SSL_CA_LOCATION",
				"KAFKA_SSL_CERT_LOCATION",
				"KAFKA_SSL_KEY_LOCATION",
			},
		},
		"rabbitmq": {
			Description: "RabbitMQ Message Queue Template",
			Entries: []string{
				"RABBITMQ_HOST",
				"RABBITMQ_PORT",
				"RABBITMQ_USER",
				"RABBITMQ_PASSWORD",
				"RABBITMQ_VHOST",
				"RABBITMQ_URL",
				"RABBITMQ_QUEUE",
				"RABBITMQ_EXCHANGE",
				"RABBITMQ_SSL",
				"RABBITMQ_SSL_CA",
			},
		},
		"redis": {
			Description: "Redis Cache Template",
			Entries: []string{
				"REDIS_HOST",
				"REDIS_PORT",
				"REDIS_URL",
				"REDIS_PASSWORD",
				"REDIS_DB",
				"REDIS_SENTINEL_HOSTS",
				"REDIS_SENTINEL_MASTER",
				"REDIS_SSL",
				"REDIS_SSL_CA",
				"REDIS_TLS",
			},
		},
		"memcached": {
			Description: "Memcached Cache Template",
			Entries: []string{
				"MEMCACHED_HOST",
				"MEMCACHED_PORT",
				"MEMCACHED_SERVERS",
				"MEMCACHED_USERNAME",
				"MEMCACHED_PASSWORD",
			},
		},
		"docker": {
			Description: "Docker Container Template",
			Entries: []string{
				"DOCKER_HOST",
				"DOCKER_TLS_VERIFY",
				"DOCKER_CERT_PATH",
				"DOCKER_CONFIG",
				"DOCKER_CONTEXT",
				"DOCKER_BUILDKIT",
				"DOCKER_REGISTRY",
				"DOCKER_USERNAME",
				"DOCKER_PASSWORD",
			},
		},
		"k8s": {
			Description: "Kubernetes Template",
			Entries: []string{
				"KUBECONFIG",
				"KUBERNETES_SERVICE_HOST",
				"KUBERNETES_SERVICE_PORT",
				"KUBERNETES_SERVICE_PORT_HTTPS",
				"KUBERNETES_NAMESPACE",
				"KUBERNETES_CLUSTER",
				"KUBERNETES_CONTEXT",
			},
		},
		"vault": {
			Description: "HashiCorp Vault Template",
			Entries: []string{
				"VAULT_ADDR",
				"VAULT_ADDRESS",
				"VAULT_TOKEN",
				"VAULT_NAMESPACE",
				"VAULT_CACERT",
				"VAULT_CAPATH",
				"VAULT_CLIENT_CERT",
				"VAULT_CLIENT_KEY",
				"VAULT_SKIP_VERIFY",
				"VAULT_TLS_SERVER_NAME",
				"VAULT_MFA",
				"VAULT_ROLE_ID",
				"VAULT_SECRET_ID",
				"VAULT_AUTH_METHOD",
				"VAULT_MOUNT",
				"VAULT_PATH",
				"VAULT_MAX_RETRIES",
				"VAULT_RATE_LIMIT",
			},
		},
		"consul": {
			Description: "HashiCorp Consul Template",
			Entries: []string{
				"CONSUL_HTTP_ADDR",
				"CONSUL_ADDR",
				"CONSUL_DATACENTER",
				"CONSUL_TOKEN",
				"CONSUL_HTTP_TOKEN",
				"CONSUL_HTTP_AUTH",
				"CONSUL_HTTP_SSL",
				"CONSUL_HTTP_SSL_VERIFY",
				"CONSUL_CACERT",
				"CONSUL_CLIENT_CERT",
				"CONSUL_CLIENT_KEY",
				"CONSUL_TLS_SERVER_NAME",
				"CONSUL_NAMESPACE",
				"CONSUL_PARTITION",
				"CONSUL_GRPC_ADDR",
				"CONSUL_GRPC_PORT",
			},
		},
		"terraform": {
			Description: "Terraform Infrastructure as Code Template",
			Entries: []string{
				"TF_LOG",
				"TF_LOG_PATH",
				"TF_INPUT",
				"TF_IN_AUTOMATION",
				"TF_DATA_DIR",
				"TF_PLUGIN_CACHE_DIR",
				"TF_CLI_CONFIG_FILE",
				"TF_REGISTRY_DISCOVERY_RETRY",
				"TF_REGISTRY_CLIENT_TIMEOUT",
				"TF_CLI_ARGS",
				"TF_CLI_ARGS_init",
				"TF_CLI_ARGS_plan",
				"TF_CLI_ARGS_apply",
				"TF_CLI_ARGS_destroy",
			},
		},
		"terragrunt": {
			Description: "Terragrunt Infrastructure as Code Template",
			Entries: []string{
				"TERRAGRUNT_CONFIG",
				"TERRAGRUNT_WORKING_DIR",
				"TERRAGRUNT_SOURCE",
				"TERRAGRUNT_SOURCE_UPDATE",
				"TERRAGRUNT_SOURCE_MAP",
				"TERRAGRUNT_DOWNLOAD",
				"TERRAGRUNT_DOWNLOAD_DIR",
				"TERRAGRUNT_IAM_ROLE",
				"TERRAGRUNT_IAM_ASSUME_ROLE_DURATION",
				"TERRAGRUNT_IAM_ASSUME_ROLE_SESSION_NAME",
				"TERRAGRUNT_PARALLELISM",
				"TERRAGRUNT_DEBUG",
				"TERRAGRUNT_LOG_LEVEL",
				"TERRAGRUNT_NO_AUTO_INIT",
				"TERRAGRUNT_NO_AUTO_RETRY",
				"TERRAGRUNT_NON_INTERACTIVE",
				"TERRAGRUNT_TFPATH",
			},
		},
		"helm": {
			Description: "Helm Kubernetes Package Manager Template",
			Entries: []string{
				"HELM_HOME",
				"HELM_CONFIG_HOME",
				"HELM_CACHE_HOME",
				"HELM_DATA_HOME",
				"HELM_DRIVER",
				"HELM_DRIVER_SQL_CONNECTION_STRING",
				"HELM_NAMESPACE",
				"HELM_KUBECONTEXT",
				"HELM_REGISTRY_CONFIG",
				"HELM_REPOSITORY_CONFIG",
				"HELM_REPOSITORY_CACHE",
				"HELM_PLUGINS",
				"HELM_MAX_HISTORY",
			},
		},
		"ansible": {
			Description: "Ansible Configuration Management Template",
			Entries: []string{
				"ANSIBLE_CONFIG",
				"ANSIBLE_HOST_KEY_CHECKING",
				"ANSIBLE_INVENTORY",
				"ANSIBLE_VAULT_PASSWORD_FILE",
				"ANSIBLE_ROLES_PATH",
				"ANSIBLE_COLLECTIONS_PATHS",
				"ANSIBLE_SSH_PIPELINING",
				"ANSIBLE_FORCE_COLOR",
				"ANSIBLE_NOCOLOR",
				"ANSIBLE_VERBOSITY",
				"ANSIBLE_TIMEOUT",
				"ANSIBLE_SSH_ARGS",
				"ANSIBLE_SSH_COMMON_ARGS",
			},
		},
		"packer": {
			Description: "HashiCorp Packer Template",
			Entries: []string{
				"PACKER_CACHE_DIR",
				"PACKER_CONFIG",
				"PACKER_CONFIG_DIR",
				"PACKER_PLUGIN_PATH",
				"PACKER_LOG",
				"PACKER_LOG_PATH",
				"PACKER_PLUGIN_MIN_PORT",
				"PACKER_PLUGIN_MAX_PORT",
				"PACKER_TMP_DIR",
				"CHECKPOINT_DISABLE",
			},
		},
		"vagrant": {
			Description: "Vagrant Virtual Machine Management Template",
			Entries: []string{
				"VAGRANT_HOME",
				"VAGRANT_CWD",
				"VAGRANT_DEFAULT_PROVIDER",
				"VAGRANT_DEFAULT_TEMPLATE",
				"VAGRANT_PREFERRED_PROVIDERS",
				"VAGRANT_VAGRANTFILE",
				"VAGRANT_DOTFILE_PATH",
				"VAGRANT_LOG",
				"VAGRANT_NO_COLOR",
				"VAGRANT_FORCE_COLOR",
				"VAGRANT_NO_PLUGINS",
				"VAGRANT_NO_PARALLEL",
				"VAGRANT_ALLOW_PLUGIN_SOURCE_ERRORS",
				"VAGRANT_BOX_UPDATE_CHECK_DISABLE",
				"VAGRANT_CHECKPOINT_DISABLE",
				"VAGRANT_SERVER_URL",
				"VAGRANT_SERVER_ACCESS_TOKEN_BY_URL",
				"VAGRANT_ALIAS_FILE",
				"VAGRANT_LOCAL_PLUGINS_LOAD",
				"VAGRANT_INSTALL_LOCAL_PLUGINS",
				"VAGRANT_PREFER_SYSTEM_BIN",
				"VAGRANT_MAX_REBOOT_RETRY_DURATION",
			},
		},
		"jira-cli": {
			Description: "Jira CLI Tool Template",
			Entries: []string{
				"JIRA_URL",
				"JIRA_USERNAME",
				"JIRA_API_TOKEN",
				"JIRA_CONFIG_FILE",
				"JIRA_PASSWORD",
				"JIRA_BEARER_TOKEN",
				"JIRA_TIMEOUT",
			},
		},
		"python": {
			Description: "Python Programming Language Template",
			Entries: []string{
				"PYTHONPATH",
				"PYTHONHOME",
				"PYTHONUNBUFFERED",
				"PYTHONDONTWRITEBYTECODE",
				"PYTHONHASHSEED",
				"PYTHONIOENCODING",
				"PYTHONSTARTUP",
				"PIP_INDEX_URL",
				"PIP_TRUSTED_HOST",
				"PIP_CACHE_DIR",
				"VIRTUAL_ENV",
				"PYENV_ROOT",
				"PYTHON_VERSION",
			},
		},
		"go": {
			Description: "Go Programming Language Template",
			Entries: []string{
				"GOPATH",
				"GOROOT",
				"GOOS",
				"GOARCH",
				"GO111MODULE",
				"GOPROXY",
				"GOSUMDB",
				"GOCACHE",
				"GOMODCACHE",
				"CGO_ENABLED",
				"CGO_CFLAGS",
				"CGO_LDFLAGS",
				"GOFLAGS",
			},
		},
		"rust": {
			Description: "Rust Programming Language Template",
			Entries: []string{
				"CARGO_HOME",
				"CARGO_TARGET_DIR",
				"CARGO_BUILD_RUSTC",
				"CARGO_BUILD_RUSTFLAGS",
				"CARGO_HTTP_TIMEOUT",
				"CARGO_HTTP_DEBUG",
				"CARGO_HTTP_CAINFO",
				"CARGO_HTTP_CHECK_REVOKE",
				"RUSTC",
				"RUSTFLAGS",
				"RUSTDOC",
				"RUSTUP_HOME",
				"RUSTUP_TOOLCHAIN",
				"RUSTUP_UPDATE_ROOT",
			},
		},
		"c": {
			Description: "C Programming Language Template",
			Entries: []string{
				"CC",
				"CXX",
				"CFLAGS",
				"CXXFLAGS",
				"CPPFLAGS",
				"LDFLAGS",
				"LD_LIBRARY_PATH",
				"PKG_CONFIG_PATH",
				"PKG_CONFIG",
				"CMAKE_PREFIX_PATH",
				"CMAKE_INCLUDE_PATH",
				"CMAKE_LIBRARY_PATH",
			},
		},
		"git": {
			Description: "Git Version Control Template",
			Entries: []string{
				"GIT_AUTHOR_NAME",
				"GIT_AUTHOR_EMAIL",
				"GIT_COMMITTER_NAME",
				"GIT_COMMITTER_EMAIL",
				"GIT_EDITOR",
				"GIT_CONFIG",
				"GIT_CONFIG_GLOBAL",
				"GIT_CONFIG_SYSTEM",
				"GIT_SSH_COMMAND",
				"GIT_HTTP_LOW_SPEED_LIMIT",
				"GIT_HTTP_LOW_SPEED_TIME",
				"GIT_SSL_NO_VERIFY",
				"GIT_TRACE",
				"GIT_CURL_VERBOSE",
				"GIT_TRACE_PACKET",
				"GIT_WORK_TREE",
				"GIT_DIR",
			},
		},
		"github": {
			Description: "GitHub Platform Template",
			Entries: []string{
				"GITHUB_TOKEN",
				"GITHUB_API_URL",
				"GITHUB_ACTIONS",
				"GITHUB_REPOSITORY",
				"GITHUB_REF",
				"GITHUB_SHA",
				"GITHUB_WORKSPACE",
				"GITHUB_RUN_ID",
				"GITHUB_RUN_NUMBER",
				"GITHUB_SERVER_URL",
				"GITHUB_ACTOR",
				"GITHUB_EVENT_NAME",
				"GITHUB_BASE_REF",
				"GITHUB_HEAD_REF",
				"GITHUB_REPOSITORY_OWNER",
				"GITHUB_REPOSITORY_OWNER_ID",
			},
		},
		"gitlab": {
			Description: "GitLab Platform Template",
			Entries: []string{
				"GITLAB_TOKEN",
				"GITLAB_API_URL",
				"CI_PROJECT_ID",
				"CI_PROJECT_NAME",
				"CI_PROJECT_PATH",
				"CI_PIPELINE_ID",
				"CI_JOB_ID",
				"CI_COMMIT_SHA",
				"CI_COMMIT_REF_NAME",
				"CI_SERVER_URL",
				"GITLAB_USER_ID",
				"GITLAB_USER_EMAIL",
				"CI_REGISTRY",
				"CI_REGISTRY_USER",
				"CI_REGISTRY_PASSWORD",
				"CI_REGISTRY_IMAGE",
				"CI_COMMIT_BRANCH",
				"CI_COMMIT_TAG",
			},
		},
		"proxy": {
			Description: "Proxy Server Configuration Template",
			Entries: []string{
				"HTTP_PROXY",
				"HTTPS_PROXY",
				"FTP_PROXY",
				"NO_PROXY",
				"http_proxy",
				"https_proxy",
				"ftp_proxy",
				"no_proxy",
				"ALL_PROXY",
				"all_proxy",
				"PROXY",
				"proxy",
				"RSYNC_PROXY",
				"rsync_proxy",
			},
		},
		"wireguard": {
			Description: "WireGuard VPN Client Template",
			Entries: []string{
				"WG_INTERFACE",
				"WG_ADDRESS",
				"WG_PRIVATE_KEY",
				"WG_PEER_PUBLIC_KEY",
				"WG_PEER_ENDPOINT",
				"WG_ALLOWED_IPS",
				"WG_PERSISTENT_KEEPALIVE",
				"WG_COLOR_MODE",
				"WG_HIDE_KEYS",
				"WG_ENDPOINT_RESOLUTION_RETRIES",
			},
		},
		"sops": {
			Description: "SOPS Secrets Operations Template",
			Entries: []string{
				"SOPS_AGE_KEY_FILE",
				"SOPS_AGE_KEY",
				"SOPS_AGE_RECIPIENTS",
				"SOPS_KMS_ARN",
				"SOPS_GCP_KMS_IDS",
				"SOPS_AZURE_KEYVAULT_URL",
				"SOPS_PGP_FP",
				"SOPS_PGP_PRIVATE_KEY",
				"SOPS_PGP_PUBLIC_KEY",
				"SOPS_VAULT_ADDR",
				"SOPS_VAULT_TOKEN",
				"SOPS_VAULT_TRANSIT_URI",
			},
		},
		"yq": {
			Description: "yq YAML Processor Template",
			Entries: []string{
				"YQ_VERSION",
				"YQ_BINARY",
			},
		},
		"jq": {
			Description: "jq JSON Processor Template",
			Entries: []string{
				"JQ_COLORS",
			},
		},
		"jo": {
			Description: "jo JSON Output Tool Template",
			Entries: []string{
				"JO_PRETTY",
			},
		},
		"etcd": {
			Description: "etcd Client Configuration Template",
			Entries: []string{
				"ETCDCTL_ENDPOINTS",
				"ETCDCTL_API",
				"ETCDCTL_CACERT",
				"ETCDCTL_CERT",
				"ETCDCTL_KEY",
				"ETCDCTL_USERNAME",
				"ETCDCTL_PASSWORD",
				"ETCDCTL_DIAL_TIMEOUT",
				"ETCDCTL_COMMAND_TIMEOUT",
				"ETCD_ENDPOINTS",
				"ETCD_CACERT",
				"ETCD_CERT",
				"ETCD_KEY",
			},
		},
		"k6": {
			Description: "k6 Load Testing Tool Template",
			Entries: []string{
				"K6_VUS",
				"K6_DURATION",
				"K6_ITERATIONS",
				"K6_STAGES",
				"K6_THRESHOLDS",
				"K6_TAGS",
				"K6_SYSTEM_TAGS",
				"K6_SUMMARY_EXPORT",
				"K6_SUMMARY_TIME_UNIT",
				"K6_SUMMARY_TREND_STATS",
				"K6_SUMMARY_MODE",
				"K6_NO_SUMMARY",
				"K6_NO_SETUP",
				"K6_NO_TEARDOWN",
				"K6_NO_THRESHOLDS",
				"K6_NO_COLOR",
				"K6_QUIET",
				"K6_VERBOSE",
				"K6_LOG_OUTPUT",
				"K6_LOG_FORMAT",
				"K6_CONSOLE_OUTPUT",
				"K6_ADDRESS",
				"K6_CONFIG",
				"K6_INCLUDE_SYSTEM_ENV_VARS",
				"K6_HTTP_DEBUG",
				"K6_MAX_REDIRECTS",
				"K6_USER_AGENT",
				"K6_BATCH",
				"K6_BATCH_PER_HOST",
				"K6_DISCARD_RESPONSE_BODIES",
				"K6_DNS",
				"K6_HOSTS",
				"K6_BLOCK_HOSTNAMES",
				"K6_BLACKLIST_IP",
				"K6_LOCAL_IPS",
				"K6_NO_COOKIES_RESET",
				"K6_NO_CONNECTION_REUSE",
				"K6_NO_VU_CONNECTION_REUSE",
				"K6_LINGER",
				"K6_TLS_CIPHER_SUITES",
				"K6_TLS_VERSION",
				"K6_INSECURE_SKIP_TLS_VERIFY",
				"K6_TLS_AUTH",
				"K6_SETUP_TIMEOUT",
				"K6_TEARDOWN_TIMEOUT",
				"K6_RPS",
				"K6_EXECUTION_SEGMENT",
				"K6_EXIT_ON_RUNNING",
				"K6_PAUSED",
				"K6_THROW",
				"K6_RESULTS_OUTPUT",
				"K6_TRACES_OUTPUT",
			},
		},
	},
}
